import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1768963681962 implements MigrationInterface {
    name = 'InitialSchema1768963681962'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "survey_response_grids" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "createdBy" character varying(255), "updatedBy" character varying(255), "version" integer NOT NULL, "questionId" uuid NOT NULL, "employeeId" uuid NOT NULL, "rowName" character varying(500) NOT NULL, "columnValue" character varying(500) NOT NULL, "submittedAt" TIMESTAMP NOT NULL, CONSTRAINT "PK_f6bdae8a2ce73c4696be91f096e" PRIMARY KEY ("id")); COMMENT ON COLUMN "survey_response_grids"."createdAt" IS '생성 일시'; COMMENT ON COLUMN "survey_response_grids"."updatedAt" IS '수정 일시'; COMMENT ON COLUMN "survey_response_grids"."deletedAt" IS '삭제 일시 (소프트 삭제)'; COMMENT ON COLUMN "survey_response_grids"."createdBy" IS '생성자 ID'; COMMENT ON COLUMN "survey_response_grids"."updatedBy" IS '수정자 ID'; COMMENT ON COLUMN "survey_response_grids"."version" IS '버전 (낙관적 잠금용)'; COMMENT ON COLUMN "survey_response_grids"."questionId" IS '질문 ID'; COMMENT ON COLUMN "survey_response_grids"."employeeId" IS '직원 ID (외부 시스템 직원 ID - SSO)'; COMMENT ON COLUMN "survey_response_grids"."rowName" IS '행 이름'; COMMENT ON COLUMN "survey_response_grids"."columnValue" IS '열 값 (선택한 값)'; COMMENT ON COLUMN "survey_response_grids"."submittedAt" IS '제출 일시'`);
        await queryRunner.query(`CREATE INDEX "idx_survey_response_grid_employee_id" ON "survey_response_grids" ("employeeId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uk_survey_response_grid" ON "survey_response_grids" ("questionId", "employeeId", "rowName") `);
        await queryRunner.query(`CREATE TABLE "survey_response_files" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "createdBy" character varying(255), "updatedBy" character varying(255), "version" integer NOT NULL, "questionId" uuid NOT NULL, "employeeId" uuid NOT NULL, "fileUrl" text NOT NULL, "fileName" character varying(500) NOT NULL, "fileSize" bigint NOT NULL, "mimeType" character varying(200) NOT NULL, "submittedAt" TIMESTAMP NOT NULL, CONSTRAINT "PK_caedd5a42637280fd8665964d76" PRIMARY KEY ("id")); COMMENT ON COLUMN "survey_response_files"."createdAt" IS '생성 일시'; COMMENT ON COLUMN "survey_response_files"."updatedAt" IS '수정 일시'; COMMENT ON COLUMN "survey_response_files"."deletedAt" IS '삭제 일시 (소프트 삭제)'; COMMENT ON COLUMN "survey_response_files"."createdBy" IS '생성자 ID'; COMMENT ON COLUMN "survey_response_files"."updatedBy" IS '수정자 ID'; COMMENT ON COLUMN "survey_response_files"."version" IS '버전 (낙관적 잠금용)'; COMMENT ON COLUMN "survey_response_files"."questionId" IS '질문 ID'; COMMENT ON COLUMN "survey_response_files"."employeeId" IS '직원 ID (외부 시스템 직원 ID - SSO)'; COMMENT ON COLUMN "survey_response_files"."fileUrl" IS '파일 URL (AWS S3)'; COMMENT ON COLUMN "survey_response_files"."fileName" IS '원본 파일명'; COMMENT ON COLUMN "survey_response_files"."fileSize" IS '파일 크기 (bytes)'; COMMENT ON COLUMN "survey_response_files"."mimeType" IS 'MIME 타입'; COMMENT ON COLUMN "survey_response_files"."submittedAt" IS '제출 일시'`);
        await queryRunner.query(`CREATE INDEX "idx_survey_response_file_employee_id" ON "survey_response_files" ("employeeId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uk_survey_response_file" ON "survey_response_files" ("questionId", "employeeId", "fileUrl") `);
        await queryRunner.query(`CREATE TABLE "survey_response_datetimes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "createdBy" character varying(255), "updatedBy" character varying(255), "version" integer NOT NULL, "questionId" uuid NOT NULL, "employeeId" uuid NOT NULL, "datetimeValue" TIMESTAMP NOT NULL, "submittedAt" TIMESTAMP NOT NULL, CONSTRAINT "PK_6bcbd586fdeb252861e8b0c2871" PRIMARY KEY ("id")); COMMENT ON COLUMN "survey_response_datetimes"."createdAt" IS '생성 일시'; COMMENT ON COLUMN "survey_response_datetimes"."updatedAt" IS '수정 일시'; COMMENT ON COLUMN "survey_response_datetimes"."deletedAt" IS '삭제 일시 (소프트 삭제)'; COMMENT ON COLUMN "survey_response_datetimes"."createdBy" IS '생성자 ID'; COMMENT ON COLUMN "survey_response_datetimes"."updatedBy" IS '수정자 ID'; COMMENT ON COLUMN "survey_response_datetimes"."version" IS '버전 (낙관적 잠금용)'; COMMENT ON COLUMN "survey_response_datetimes"."questionId" IS '질문 ID'; COMMENT ON COLUMN "survey_response_datetimes"."employeeId" IS '직원 ID (외부 시스템 직원 ID - SSO)'; COMMENT ON COLUMN "survey_response_datetimes"."datetimeValue" IS '날짜/시간 값'; COMMENT ON COLUMN "survey_response_datetimes"."submittedAt" IS '제출 일시'`);
        await queryRunner.query(`CREATE INDEX "idx_survey_response_datetime_employee_id" ON "survey_response_datetimes" ("employeeId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uk_survey_response_datetime" ON "survey_response_datetimes" ("questionId", "employeeId") `);
        await queryRunner.query(`CREATE TYPE "public"."attendees_status_enum" AS ENUM('pending', 'in_progress', 'completed', 'overdue')`);
        await queryRunner.query(`CREATE TABLE "attendees" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "createdBy" character varying(255), "updatedBy" character varying(255), "version" integer NOT NULL, "educationManagementId" uuid NOT NULL, "employeeId" uuid NOT NULL, "status" "public"."attendees_status_enum" NOT NULL DEFAULT 'pending', "completedAt" TIMESTAMP, CONSTRAINT "PK_0d01acb0e67860db61a6fb61a4a" PRIMARY KEY ("id")); COMMENT ON COLUMN "attendees"."createdAt" IS '생성 일시'; COMMENT ON COLUMN "attendees"."updatedAt" IS '수정 일시'; COMMENT ON COLUMN "attendees"."deletedAt" IS '삭제 일시 (소프트 삭제)'; COMMENT ON COLUMN "attendees"."createdBy" IS '생성자 ID'; COMMENT ON COLUMN "attendees"."updatedBy" IS '수정자 ID'; COMMENT ON COLUMN "attendees"."version" IS '버전 (낙관적 잠금용)'; COMMENT ON COLUMN "attendees"."educationManagementId" IS '교육 관리 ID'; COMMENT ON COLUMN "attendees"."employeeId" IS '직원 ID (외부 시스템 직원 ID - SSO)'; COMMENT ON COLUMN "attendees"."status" IS '수강 상태 (pending|in_progress|completed|overdue)'; COMMENT ON COLUMN "attendees"."completedAt" IS '완료 일시'`);
        await queryRunner.query(`CREATE INDEX "idx_attendee_status" ON "attendees" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_attendee_employee_id" ON "attendees" ("employeeId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uk_attendee" ON "attendees" ("educationManagementId", "employeeId") `);
        await queryRunner.query(`CREATE TYPE "public"."education_managements_status_enum" AS ENUM('scheduled', 'in_progress', 'completed', 'cancelled', 'postponed')`);
        await queryRunner.query(`CREATE TABLE "education_managements" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "createdBy" character varying(255), "updatedBy" character varying(255), "version" integer NOT NULL, "title" character varying(500) NOT NULL, "content" text NOT NULL, "isPublic" boolean NOT NULL DEFAULT true, "status" "public"."education_managements_status_enum" NOT NULL DEFAULT 'scheduled', "managerId" uuid NOT NULL, "deadline" TIMESTAMP NOT NULL, "attachments" jsonb, "order" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_7b54f712d5bbab11544e0aca398" PRIMARY KEY ("id")); COMMENT ON COLUMN "education_managements"."createdAt" IS '생성 일시'; COMMENT ON COLUMN "education_managements"."updatedAt" IS '수정 일시'; COMMENT ON COLUMN "education_managements"."deletedAt" IS '삭제 일시 (소프트 삭제)'; COMMENT ON COLUMN "education_managements"."createdBy" IS '생성자 ID'; COMMENT ON COLUMN "education_managements"."updatedBy" IS '수정자 ID'; COMMENT ON COLUMN "education_managements"."version" IS '버전 (낙관적 잠금용)'; COMMENT ON COLUMN "education_managements"."title" IS '교육 제목'; COMMENT ON COLUMN "education_managements"."content" IS '교육 내용'; COMMENT ON COLUMN "education_managements"."isPublic" IS '공개 여부'; COMMENT ON COLUMN "education_managements"."status" IS '상태 (scheduled|in_progress|completed|cancelled|postponed)'; COMMENT ON COLUMN "education_managements"."managerId" IS '담당자 ID (외부 시스템 직원 ID - SSO)'; COMMENT ON COLUMN "education_managements"."deadline" IS '교육 마감 일시'; COMMENT ON COLUMN "education_managements"."attachments" IS '첨부파일 목록 (AWS S3 URLs)'; COMMENT ON COLUMN "education_managements"."order" IS '정렬 순서'`);
        await queryRunner.query(`CREATE INDEX "idx_education_management_order" ON "education_managements" ("order") `);
        await queryRunner.query(`CREATE INDEX "idx_education_management_deadline" ON "education_managements" ("deadline") `);
        await queryRunner.query(`CREATE INDEX "idx_education_management_manager_id" ON "education_managements" ("managerId") `);
        await queryRunner.query(`CREATE INDEX "idx_education_management_is_public" ON "education_managements" ("isPublic") `);
        await queryRunner.query(`CREATE INDEX "idx_education_management_status" ON "education_managements" ("status") `);
        await queryRunner.query(`ALTER TABLE "attendees" ADD CONSTRAINT "FK_a68f18ef8d97baa19b957f2600b" FOREIGN KEY ("educationManagementId") REFERENCES "education_managements"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "attendees" DROP CONSTRAINT "FK_a68f18ef8d97baa19b957f2600b"`);
        await queryRunner.query(`DROP INDEX "public"."idx_education_management_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_education_management_is_public"`);
        await queryRunner.query(`DROP INDEX "public"."idx_education_management_manager_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_education_management_deadline"`);
        await queryRunner.query(`DROP INDEX "public"."idx_education_management_order"`);
        await queryRunner.query(`DROP TABLE "education_managements"`);
        await queryRunner.query(`DROP TYPE "public"."education_managements_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."uk_attendee"`);
        await queryRunner.query(`DROP INDEX "public"."idx_attendee_employee_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_attendee_status"`);
        await queryRunner.query(`DROP TABLE "attendees"`);
        await queryRunner.query(`DROP TYPE "public"."attendees_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."uk_survey_response_datetime"`);
        await queryRunner.query(`DROP INDEX "public"."idx_survey_response_datetime_employee_id"`);
        await queryRunner.query(`DROP TABLE "survey_response_datetimes"`);
        await queryRunner.query(`DROP INDEX "public"."uk_survey_response_file"`);
        await queryRunner.query(`DROP INDEX "public"."idx_survey_response_file_employee_id"`);
        await queryRunner.query(`DROP TABLE "survey_response_files"`);
        await queryRunner.query(`DROP INDEX "public"."uk_survey_response_grid"`);
        await queryRunner.query(`DROP INDEX "public"."idx_survey_response_grid_employee_id"`);
        await queryRunner.query(`DROP TABLE "survey_response_grids"`);
    }

}
